document.writeln("    <div class=\'foot\'>");
document.writeln("        <div class=\'foot_m\'>");
document.writeln("            ");
document.writeln("            <div class=\'foot-list foot-list-01\'>");
document.writeln("                <h2>");
document.writeln("                    关于我们</h2>");
document.writeln("                <p>");
document.writeln("                    驭智家商贸工作室专注服务外贸网络推广10年，是海外精准营销服务商，谷歌广告运营商，俄罗斯Yandex授权代理商，微软bing搜索授权代理商，韩国Naver授...");
document.writeln("                </p>");
document.writeln("                <a class=\'about-button\' href=\'About.html\' >查看更多 >></a>");
document.writeln("            </div>");
document.writeln("<div class=\'foot-list foot-list-02\'>");
document.writeln("                <h2>");
document.writeln("                    友情链接</h2>");
document.writeln("<a class=\'foot-list-nav\' href=\'http://www.yz838.com\' target=\'_blank\'>华夏中医云诊所</a> ");
document.writeln("<a class=\'foot-list-nav\' href=\'https://yz838.com\' target=\'_blank\'>华夏中医</a> ");
document.writeln("<a class=\'foot-list-nav\' href=\'http://www.shuize.top:8035/im/text/104eac.html\' target=\'_blank\'>远程问诊</a> ");
document.writeln("<a class=\'foot-list-nav\' href=\'https://yz838.com/160.html\' target=\'_blank\'>师承中医师</a> ");
document.writeln("<a class=\'foot-list-nav\' href=\'https://yz838.com/161.html\' target=\'_blank\'>本科学历提示</a>");
document.writeln("<a class=\'foot-list-nav\' href=\'https://maicai.yz838.com\' target=\'_blank\'>田心东楼菜篮子</a>");
document.writeln("            </div>");
document.writeln("            <div class=\'foot-list foot-list-03\'>");
document.writeln("                <h2>");
document.writeln("                    快捷链接</h2>");
document.writeln("<a class=\'foot-list-nav\' href=\'http://www.shuize.top:8035/\' target=\'_blank\'>问诊系统</a> ");
document.writeln("<a class=\'foot-list-nav\' href=\'http://www.shuize.top:88\' target=\'_blank\'>门诊管理</a> ");
document.writeln("<a class=\'foot-list-nav\' href=\'http://www.shuize.top:90\' target=\'_blank\'>项目管理</a> ");
document.writeln("<a class=\'foot-list-nav\' href=\'http://www.shuize.top:91\' target=\'_blank\'>书签管理</a> ");
document.writeln("<a class=\'foot-list-nav\' href=\'http://www.shuize.top:89/2.html\' target=\'_blank\'>资源日记</a>");
document.writeln("<a class=\'foot-list-nav\' href=\'https://shuize.top\' target=\'_blank\'>外贸导航</a>");
document.writeln("            </div>");
document.writeln("            <div class=\'foot-list foot-list-04\'>");
document.writeln("                <h2 style=\'\'>");
document.writeln("                    驭智家 微信公众号</h2>");
document.writeln("                周一至周五 8:30-17:30");
document.writeln("                <br />");
document.writeln("                微信扫一扫 搜索驭智家为您服务");
document.writeln("                <br />");
document.writeln("                <img alt=\'weixin\' src=\'images/code1.png\'  width=\'90\' height=\'90\' />");
document.writeln("            </div>");
document.writeln("        </div>");
document.writeln("        <div class=\'foot-o\'>");
document.writeln("            <div class=\'foot-o-nav\'>");
document.writeln("                <p>Copyright <a href=\'https://wm.yz838.com\'>驭智家商贸工作室</a> Rights Reserved.<script type=\'text/javascript\' src=\'https://js.users.51.la/21441251.js\'></script></p>");
document.writeln("            </div>");
document.writeln("        </div>");
document.writeln("    </div>");
document.writeln("    <div class=\'contact_f\'>");
document.writeln("        <table width=\'94%\' border=\'0\' cellspacing=\'0\' cellpadding=\'0\' style=\'margin: auto;\'>");
document.writeln("            <tr>");
document.writeln("                <td>");
document.writeln("                    <img src=\'images/icon_14.png\'  /><br />");
document.writeln("                    <a href=\'index.html\' >返回首页</a>");
document.writeln("                </td>");
document.writeln("                <td>");
document.writeln("                    <img src=\'images/icon_11.png\'  /><br />");
document.writeln("                    <a href=\'Overseas.html\'>海外推广</a>");
document.writeln("                </td>");
document.writeln("                <td>");
document.writeln("                    <img src=\'images/icon_12.png\'  /><br />");
document.writeln("                    <a href=\'tel:15219407427\'>拨打电话</a>");
document.writeln("                </td>");
document.writeln("                <td>");
document.writeln("                    <img src=\'images/icon_13.png\'  /><br />");
document.writeln("                    <a href=\'About.html\'>关于我们</a>");
document.writeln("                </td>");
document.writeln("            </tr>");
document.writeln("        </table>");
document.writeln("    </div>");
document.writeln("    <div class=\'left-toolbar\'>");
document.writeln("        <ul>");
document.writeln("            <li><a href=\'\'>");
document.writeln("                <span class=\'bar01\'></span>");
document.writeln("                <label>");
document.writeln("                    在线咨询</label></a> </li>");
document.writeln("            <li><a href=\'javascript:void(0)\'><span class=\'bar02\'></span>");
document.writeln("                <label>");
document.writeln("                    15219407427</label></a> </li>");
document.writeln("            <li><a href=\'javascript:void(0)\' onClick=\'ReturnTop();\'><span class=\'bar03\'></span>");
document.writeln("                <label>");
document.writeln("                    返回顶部</label></a> </li>");
document.writeln("        </ul>");
document.writeln("    </div>");
document.writeln("    <script src=\'js/wow.min.js\' ></script>");
document.writeln("    <script>");
document.writeln("        if (!(/msie [6|7|8|9]/i.test(navigator.userAgent))) {");
document.writeln("            new WOW().init();");
document.writeln("        };");
document.writeln("    </script>");
document.writeln("    <!--<div class=\'xs-message\'>");
document.writeln("		<script language=\'javascript\' src=\'../dkb.duokebo.com/js/detector.aspx-siteid=837766\' ></script>");
document.writeln("	</div>-->");
document.writeln("	");
document.writeln("    <!-- JiaThis Button BEGIN");
document.writeln("    <script type=\'text/javascript\' src=\'../v3.jiathis.com/code/jiathis_r.js-type=left&move=0\' ");
document.writeln("        charset=\'utf-8\'></script>-->");
document.writeln("    <!-- JiaThis Button END -->");
document.writeln("</body>");
document.writeln("</html>");